config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/not_found', to: 'welcome#not_found', as: 'not_found'

  get '/people', to: 'users#index', as: 'users'
  get '/profile/:id', to: 'users#show', as: 'show_user'
  get '/people/new', to: 'users#new', as: 'new_user'
  get '/profile/:id/edit', to: 'users#edit', as: 'edit_user'
  post '/people/new', to: 'users#create', as: 'create_user'
  post '/profile/:id/edit', to: 'users#update', as: 'update_user'
  delete '/profile/:id/delete', to: 'users#delete', as: 'delete_user'

  get '/restaurants', to: 'restaurants#index', as: 'restaurants'
  get '/restaurant/:id', to: 'restaurants#show', as: 'show_restaurant'
  get '/restaurants/new', to: 'restaurants#new', as: 'new_restaurant'
  get '/restaurant/:id/edit', to: 'restaurants#edit', as: 'edit_restaurant'
  post '/restaurants/new', to: 'restaurants#create', as: 'create_restaurant'
  patch '/restaurant/:id/edit', to: 'restaurants#update', as: 'update_restaurant'
  delete '/restaurant/:id/delete', to: 'restaurants#delete', as: 'delete_restaurant'

  get '/restaurant/:id/rate', to: 'piggies#new', as: 'new_piggy'
  get '/restaurant/:restaurant_id/:id/edit', to: 'piggies#edit', as: 'edit_piggy'
  post '/restaurant/:id/rate', to: 'piggies#create', as: 'create_piggy'
  patch '/restaurant/:restaurant_id/:id/edit', to: 'piggies#update', as: 'update_piggy'

  get '*path' => redirect('/not_found')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/piggy.rb
class Piggy < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  validates :score, inclusion: { in: (1..5) }, presence: true
  validates :restaurant, uniqueness: { scope: :user }

  def matching_user?(to_check)
    user == to_check
  end

  def matching_restaurant?(to_check)
    restaurant == to_check
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  attr_accessor :map_url_unparsed

  has_many :piggies, dependent: :destroy
  has_many :users, through: :piggies

  validates :name, presence: true, uniqueness: true

  before_save :parse_map_url

  def mean_score_by_user(subgroup)
    sum = 0.0
    divisor = 0
    subgroup.each do |subuser|
      piggy = subuser.piggy_by_restaurant(self)
      if piggy
        sum += piggy.score
        divisor += 1
      end
    end
    return sum / divisor
  end

  def mean_score_all
    sum = 0.0
    piggies.each do |piggy|
      sum += piggy.score
    end
    return sum / piggies.size
  end

  def parse_map_url
    unless map_url_unparsed.blank?
      split_url =  map_url_unparsed.split('"')
      if split_url[0] == '<iframe src='
        self.map_url = split_url[1]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :piggies, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  #attr_accessor :password

  #validates :username, presence: true, uniqueness: true
  #validates :password, presence: true, on: :create, confirmation: true

  #before_save :encrypt_password

  def piggy_by_restaurant(restaurant)
    piggies.each do |piggy|
      if piggy.restaurant == restaurant
        piggy
      end
    end
    nil
  end

  #def self.authenticate(username, password)
  #  user = find_by_username(username)
  #  if user
  #    expected_ep = BCrypt::Engine.hash_secret(password, user.salt)
  #    if user.encrypted_password == expected_ep
  #      return user
  #    end
  #  end
  #  return nil
  #end

  #def encrypt_password
  #  self.salt = BCrypt::Engine.generate_salt
  #  self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound do |exception|
    redirect_to not_found_path
  end

  def require_login
    if session[:user_id] and User.find(session[:user_id])
      yield
    else
      redirect_to login_url
    end
  end

  def require_no_login
    if session[:user_id] and User.find(session[:user_id])
      redirect_to show_user_url
    else
      yield
    end
  end
end

app/controllers/piggies_controller.rb
class PiggiesController < ApplicationController
  def new
    @piggy = Piggy.new
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @piggy = Piggy.new(piggy_params)
    if @piggy.save
      redirect_to show_restaurant_path(params[:id])
    else
      @restaurant = Restaurant.find(params[:id])
      render 'new'
    end
  end

  def edit
    @piggy = Piggy.find(params[:id])
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def update
    @piggy = Piggy.find(params[:id])
    if @piggy.update(piggy_params)
      redirect_to show_restaurant_path(params[:restaurant_id])
    else
      render 'edit'
    end
  end

  private
    def piggy_params
      params.require(:piggy).permit(:user_id, :restaurant_id, :score, :comment)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to show_restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to show_restaurant_path(@restaurant)
    else
      render 'edit'
    end
  end

  def delete
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private
    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :map_url_unparsed, :tags)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to show_user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update
      redirect_to show_user_path(@user)
    else
      render 'edit'
    end
  end

  def delete
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :blurb) #, :username, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def not_found
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/piggies_helper.rb
module PiggiesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PiggyLunch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/piggies/_form.html.erb
<%= form_for @piggy, url: url  do |f| %>
  <%= f.hidden_field :restaurant_id, value: @restaurant.id %>  
  <p>
    Who are you?<br>
    <%= f.select :user_id, User.all.collect { |u| [u.name, u.id] } %>
  <p>
    Score (1 through 5 piggies)<br>
    <%= f.number_field :score %>
  </p>
  <p>
    Comment<br>
    <%= f.text_area :comment %>
  </p>
  <p>
    <%= f.submit submit_msg %>
  </p>
<% end %>

app/views/piggies/edit.html.erb
<%= render 'shared/header', title: 'Edit your Piggy' %>

<div id='body'>
  <%= render 'shared/errors', container: @piggy %>
  <%= render 'form', url: update_piggy_path(restaurant_id: @restaurant, id: @piggy), submit_msg: 'Save Changes' %>
  <div id='foot_links'>
    <%= link_to 'Cancel', :back %>
  <%#  <%= link_to 'Cancel', show_restaurant_path(@restaurant) %>
  </div>
</div>

app/views/piggies/new.html.erb
<%= render 'shared/header', title: 'Give Piggies!' %>

<div id='body'>
  <%= render 'shared/errors', container: @piggy %>
  <%= render 'form', url: create_piggy_path(@restaurant), submit_msg: 'Submit Piggy!' %>
  <div id='foot_links'>
    <%= link_to 'Cancel', show_restaurant_path(@restaurant) %>
  </div>
</div>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, url: url do |f| %>
  <p>
    Restaurant Name <br>
    <%= f.text_field :name %>
  </p>
  <p>
    Tags <br>
    <%= f.text_field :tags %>
  </p>
  <p>
    Description <br>
    <%= f.text_area :description %>
  </p>
  <p>
    Map <br>
    <%= f.text_area :map_url_unparsed %>
  </p>
  <p>
    <%= f.submit submit_msg %>
  </p>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'shared/header', title: 'Edit Restaurant' %>

<div id='body'>
  <%= render 'shared/errors', container: @restaurant %>
  <%= render 'form', url: update_restaurant_path(@restaurant), submit_msg: 'Save Changes' %>
  <div id='foot_links'>
    <%= link_to 'Cancel', show_restaurant_path(@restaurant) %>
  </div>
</div>

app/views/restaurants/index.html.erb
<%= render 'shared/header', title: 'Restaurants' %>

<div id="body">
  <p><%= link_to 'Add a New Restaurant', new_restaurant_path %></p>
  <% @restaurants.each do |restaurant| %>
    <p><%= link_to restaurant.name, show_restaurant_path(restaurant) %></p>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<%= render 'shared/header', title: 'Add a New Restaurant' %>

<div id='body'>
  <%= render 'shared/errors', container: @restaurant %>
  <%= render 'form', url: new_restaurant_path, submit_msg: 'Add Restaurant!' %>
  <div id='foot_links'>
    <%= link_to 'Cancel', restaurants_path %>
  </div>
</div>

app/views/restaurants/show.html.erb
<%= render 'shared/header', title: @restaurant.name %>

<div id='body'>
  <p>
    <%= @restaurant.mean_score_all %> piggies over all users
  </p>
  
  <p>
    <%= @restaurant.tags %>
  </p>
  
  <p>
    <%= @restaurant.description %>
  </p>
  
  <% unless @restaurant.map_url.blank? %>
    <iframe src=<%= @restaurant.map_url %> width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
  <% end %>
  
  <p>
    <%= link_to 'Submit your Piggy Rating!', new_piggy_path %>
  </p>
  
  <div id='restaurant_piggies'>
    <% @restaurant.piggies.each do |piggy| %>
      <div class='piggy'>
        <p>
          <%= link_to piggy.user.name, show_user_path(piggy.user) %>
        </p>
        <p>
          <%= piggy.score %>
        </p>
        <p>
          <%= piggy.comment %>
        </p>
        <p>
          <%= link_to 'Edit this Piggy', edit_piggy_path(restaurant_id: @restaurant, id: piggy) %>
        </p>
      </div>
    <% end %>
  </div>
  
  <div id='foot_links'>  
    <%= link_to 'Edit this Restaurant', edit_restaurant_path(@restaurant) %>
    <%= link_to 'Delete this Restaurant', delete_restaurant_path(@restaurant) %>
    <%= link_to 'Go Back to Restaurant List', restaurants_path %>
  </div>
</div>

app/views/shared/_errors.html.erb
<div id='error_msgs'>
    <% container.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
    <% end %>
</div>

app/views/shared/_header.html.erb
<div id='header'>
  <div id='home_logo'>
    <%= link_to image_tag("sign.png"), root_path, id: 'home_text' %>
  </div>
  <div id='page_title'>
    <%= title %>
  </div>
  <div class='header_tab' id='restaurant_tab'>
    <%= link_to 'Restaurants', restaurants_path %>
  </div>
  <div class='header_tab' id='user_tab'>
    <%= link_to 'People', users_path %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user, url: url do |f| %>
  <p>Name</p>
  <%= f.text_field :name %><br>
  <%= f.submit submit_msg %>
<% end %>

app/views/users/edit.html.erb
<%= render 'shared/header', title: 'Edit this User' %>

<div id='body'>
  <%= render 'shared/errors', container: @user %>
  <%= render 'form', url: update_user_path(@user), submit_msg: 'Save Changes' %>
  <div id='foot_links'>
    <%= link_to 'Cancel', show_user_path(@user) %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'shared/header', title: 'People' %>

<div id='body'>
  <p><%= link_to 'Create a New User', new_user_path %></p>
  <% @users.each do |user| %>
    <p><%= link_to user.name, show_user_path(user) %></p>
  <% end %>
</div>

app/views/users/new.html.erb
<%= render 'shared/header', title: 'Register a New User' %>

<div id='body'>
  <%= render 'shared/errors', container: @user %>
  <%= render 'form', url: create_user_path, submit_msg: 'Register!' %>
  <div id='foot_links'>
    <%= link_to 'Cancel', users_path %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'shared/header', title: @user.name + "'s Profile" %>

<div id='body'>
  <p>
    <%= @user.blurb %>
  </p>
  
  <p>
    <%= @user.name %>'s piggies:
  </p>
  <% @user.piggies.each do |piggy| %>  
    <p>
      <%= link_to piggy.restaurant.name, show_restaurant_path(piggy.restaurant) %><br>
      <%= piggy.score %><br>
      <%= piggy.comment %><br>
      <%= link_to "Edit this Piggy", edit_piggy_path(piggy.restaurant, piggy) %>
    </p>
  <% end %>
  
  <div id='foot_links'>
    <%= link_to 'Edit this User', edit_user_path(@user) %>
    <%= link_to 'Delete this User', delete_user_path(@user) %>
    <%= link_to 'Back to People', users_path %>
  </div>
</div>

app/views/welcome/index.html.erb
<%= render 'shared/header', title: 'Welcome to Piggy Lunch!' %>

<div id='body'>
  <p>TODO: what to put here</p>
</div>

app/views/welcome/not_found.html.erb
<%= render 'shared/header', title: 'Page Not Found' %>

<div id='body'>
  <p>
    Oops! It looks like the page you are looking for doesn't exist.
  </p>
  
  <p>
    <%= link_to 'Go Back', :back %>
    or
    <%= link_to 'Go Home', root_path %>
  </p>
</div>  